# Default values for app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  registry: docker.io
  repository: gopikrishna99899/mynodeapp
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: latest

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

secret:
  enabled: true
  name: mongosecret
  data:
    MONGODB_PASS: a3Jpc2huYTc=

configMap:
  enabled: true
  name: mongoconfigmap
  data:
    MONGODB_HOST: "mymongo"
    MONGODB_PORT: "27017"
    MONGODB_DB: "test"
    MONGODB_USER: "krishna"


podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: LoadBalancer
  port: 8080
  targetPort: 8080
  # nodePort: 32761


resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi



mongodb:
  auth:
    enabled: true
    rootUser: root
    rootPassword: krishna7
    usernames: ["krishna"]
    passwords: ["krishna7"]
    databases: ["test"]

  service:
    nameOverride: mymongo
    type: ClusterIP
    ports:
      mongodb: 27017



